### ISSUE TITLE
Support for Session Token

### ISSUE THREAD

**Issue by cah-ellery-blank** [cyberark/SkyArk#3] opened 2019-05-22 20:52 UTC
We only allow STS temporary API keys and Session Token.

When running Download-CloudTrailLogFiles I get the following error:

"Get-S3Object : The AWS Access Key Id you provided does not exist in our records."
AWStrace.ps1:194 char:16

My temporary keys are correct and I can do aws s3 ls and Get-S3Object commands from the command line.

**Comment by cah-ellery-blank** [comment] 2019-05-23 16:34
Could it use a Profile that is already created?  It prompts me for API keys every time.

**Comment by Hechtov** [comment] 2019-07-13 17:59
Thanks @cah-ellery-blank for opening this issue, as we see it, it's a feature request and not a bug.
AWStealth was intended to work with AWS access keys and not with session tokens.
We agree that support in Session Token is great idea and also the idea for using local configured Profiles that were already created.
We will close this issue for now, those two possible features ideas were added to our future list.
BTW, you are welcome to try the new scanning module - AzureStealth for Azure, and share more feedback.
Thanks.

**Closed as completed by Hechtov** 2019-07-13 17:59 UTC
