### ISSUE TITLE
AWStealth returns version error for AWS Tools for Powershell version 4.x

### ISSUE THREAD

**Issue by brandond** [cyberark/SkyArk#6] opened 2019-11-21 23:17 UTC
The code at 
https://github.com/cyberark/SkyArk/blob/650138a02278f98449f99430964ac43c81f032ba/AWStealth/AWStealth.ps1#L1139 doesn't work as intended. You should probably just compare the module version to `[System.Version]"3.3.330"`.

**Comment by Hechtov** [comment] 2019-11-27 13:44
Hi @brandond 
Thanks for sharing this issue, can you elaborate on this "work as intended"?
Did the scan encounter errors for you and stopped? Did you have a greater/equal version than 3.3.330 and this filter didn't catch this?
Thanks.

**Comment by brandond** [comment] 2019-11-27 19:21
The nested version tests don't do what you intend, since they check each part of the version independently. The script itself runs fine, other than printing a big warning about the module version being too old.

**Comment by Hechtov** [comment] 2020-01-20 12:33
The nested version tests indeed check each part of the version independently as it should (it independently but each check related on the previous one...) . It starts with the "Major" version number, and only if the Major level is 3 or above it continues to test the Minor version, if the Minor is also 3 or above, only then it checks the Build number. 
Sorry, I couldn't reproduce the issue you encountered. I'm closing this issue for now.
If you think this is still an issue, please reopen the ticket, and also send me the specific AWS PowerShell version that you are using. Thanks.

**Closed as completed by Hechtov** 2020-01-20 12:33 UTC

**Comment by Hechtov** [comment] 2020-08-18 17:01
Ha ha, suddenly I understood the error you mentioned and this week I fixed that AWS module version validation logic.. Feel free to check it out :)
Thanks @brandond
